#!/bin/sh

pandoc main.md --toc --default-image-extension=png -o main.html
pandoc proposal.md -o proposal.html

pandoc main.md --toc --default-image-extension=png -o main.pdf
pandoc proposal.md -o proposal.pdf

echo "word count:" `wc -w main.md`



