#!/bin/sh

# This script generates the markdown versions of the Javascript source so that
# Pandoc can later turn them into a PDF.

cd ../src

SOURCE_APPENDIX_MARKDOWN_DIR=main/7b_Appendix_oboe_source

SRC_FILES=$(ls *.js | sort) 

FIRST=1

cd ../writing

rm $SOURCE_APPENDIX_MARKDOWN_DIR/*.md 

for JS_FILE_NAME in $SRC_FILES; do
   MD_FILE=$SOURCE_APPENDIX_MARKDOWN_DIR/$JS_FILE_NAME.md
   
   echo "will package source for appendix $MD_FILE"

   touch $MD_FILE
   
   echo > $MD_FILE  
   
   if [ $FIRST -ne 1 ]
   then
      echo "\pagebreak" >> $MD_FILE      
   fi
   
   FIRST=0    
       
   echo >> $MD_FILE         
   echo $JS_FILE_NAME >> $MD_FILE
   echo "---" >> $MD_FILE
   echo >> $MD_FILE    
   
   echo "~~~~ {.javascript}" >> $MD_FILE
   cat ../src/$JS_FILE_NAME >> $MD_FILE
   echo >> $MD_FILE
   echo "~~~~" >> $MD_FILE
   echo >> $MD_FILE                 
     
done