language: node_js
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"

jobs: 
  include:
    - stage: chrome-based-tests
      node_js: 9
      before_install:
        - npm i puppeteer
      script: npm run test-chrome-based
      