#!/bin/bash

# Since the grunt jstd plugin doesn't support v3, here's a little
# shell script to do the same. Usage is:
#
#   build.sh            # run all tests
#   build.sh foo.bar    # build but only run test foo.bar

# Edit these variables to suit your install:
JSTD_JAR=~/dev/jstestdriver/JsTestDriver-1.3.5.jar
SERVER=http://localhost:4224
BASEPATH=~/Sites/progressivejson/

# We need the slow number server we just created to be available on the same domain as the 
# jstd server to get around the browser's same origin policy.
#
# Unfortunately, jstd's proxy feature doesn't support streaming http (it waits for the whole
# request and propagates). Luckily, this isn't too difficult to make in Node
#
# For now, start /tests/slowserver/proxy.js prior to starting browser instances.

function runjstd {
   echo "Will run oboe json tests(" ${TESTS} ") against $1"
   java -jar ${JSTD_JAR} --captureConsole --config test/jsTestDriver-${1}.conf --server ${SERVER} --tests ${TESTS} --basePath ${BASEPATH} --reset   
}

if [ "$1" ] ; then
  TESTS=$1
else
  echo "no tests specified, will run all"
  TESTS=all
fi

echo "building at $(date)"

runjstd dev
 
env grunt 

runjstd concat 

runjstd minified 

mv dist/oboe.concat.js dist/oboe.js 
 
