#!/bin/sh

# Simple shell script. Reads all of the file in the markdown directory in order, and writes 
# out their contents with two newlines seperating the individual files.
# With thanks to: http://stackoverflow.com/questions/2576693/linux-merging-multiple-files-each-on-a-new-line 

FILE_LIST=$(find markdown -name "*.md" | sort)

for f in $FILE_LIST; do
   # need to make footnote names unique by prepending the file they come from:
    
   filename=$(basename $f .md)
   cat $f | sed -E "s/\[\^([0-9])\]/[^$filename\1]/g" 
   
   echo; echo
done
