#!/bin/sh

pandoc proposal.md -o main/proposal.pdf

echo made proposal pdf

./scripts/gen_source_appendix

./scripts/all_markdown > main/main.md

echo made main md 

./scripts/all_markdown | pandoc -f markdown+autolink_bare_uris --smart --toc --default-image-extension=png --number-sections --bibliography=bibliography.json --template=scripts/mainOboeTemplate --to latex --output=main/main.tex

echo made main tex

echo making main pdf...
 
./scripts/all_markdown | pandoc -f markdown+autolink_bare_uris --smart --toc --default-image-extension=png --number-sections --bibliography=bibliography.json --template=scripts/mainOboeTemplate --output=main/main.pdf

echo ...done

wc -w markdown/*.md
wc -w proposal.md




